ARG CODE_VERSION=22.04

FROM ubuntu:${CODE_VERSION} 

RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /home/code

ENV USER=chunche95
ENV SHELL=/bin/bash
ENV LOGNAME=chunche

CMD [ "bash" ]